---
- name: "AUTOMATED | 6.1.2 | PATCH | Ensure permissions on /etc/passwd are configured"
  file:
      path: /etc/passwd
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.2
      - permissions

- name: "AUTOMATED | 6.1.3 | PATCH | Ensure permissions on /etc/passwd- are configured"
  file:
      path: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.3
      - permissions

- name: "AUTOMATED | 6.1.4 | PATCH | Ensure permissions on /etc/group are configured"
  file:
      path: /etc/group
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.4
      - permissions

- name: "AUTOMATED | 6.1.5 | PATCH | Ensure permissions on /etc/group- are configured"
  file:
      path: /etc/group-
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.5
      - permissions

- name: "AUTOMATED | 6.1.6 | PATCH | Ensure permissions on /etc/shadow are configured"
  file:
      path: /etc/shadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.6
      - permissions

- name: "AUTOMATED | 6.1.7 | PATCH | Ensure permissions on /etc/shadow- are configured"
  file:
      path: /etc/shadow-
      owner: root
      group: shadow
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.7
      - permissions

- name: "AUTOMATED | 6.1.8 | PATCH | Ensure permissions on /etc/gshadow are configured"
  file:
      path: /etc/gshadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_8
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.8
      - permissions

- name: "AUTOMATED | 6.1.9 | PATCH | Ensure permissions on /etc/gshadow- are configured"
  file:
      path: /etc/gshadow-
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_9
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.9
      - permissions
