---
- name: "AUTOMATED | 1.6.1.1 | PATCH | Ensure AppArmor is installed"
  apt:
      name: ['apparmor', 'apparmor-utils']
      state: present
  when:
      - ubtu18cis_rule_1_6_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.1
      - apparmor

- name: "AUTOMATED | 1.6.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - ubtu18cis_rule_1_6_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.1.3
      - apparmor

- name: "AUTOMATED | 1.6.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - ubtu18cis_rule_1_6_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_1.6.1.4
      - apparmor
