---
- name: "AUTOMATED | 1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  block:
      - name: "AUTOMATED | 1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set ASLR settings"
        lineinfile:
            path: /etc/sysctl.conf
            regexp: '^kernel.randomize_va_space'
            line: 'kernel.randomize_va_space = 2'

      - name: "AUTOMATED | 1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
        sysctl:
            name: kernel.randomize_va_space
            value: '2'
  when:
      - ubtu18cis_rule_1_5_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.2
      - aslr

- name: "AUTOMATED | 1.5.3 | PATCH | Ensure prelink is disabled"
  block:
      - name: "AUTOMATED | 1.5.3 | PATCH | Ensure prelink is disabled | Restore binaries to normal"
        command: prelink -ua
        changed_when: false
        failed_when: false

      - name: "AUTOMATED | 1.5.3 | PATCH | Ensure prelink is disabled | Remove prelink package"
        apt:
            name: prelink
            state: absent
  when:
      - ubtu18cis_rule_1_5_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.3
      - prelink

- name: "AUTOMATED | 1.5.4 | PATCH | Ensure core dumps are restricted"
  block:
      - name: "AUTOMATED | 1.5.4 | PATCH | Ensure core dumps are restricted"
        lineinfile:
            path: /etc/security/limits.conf
            regexp: '^#?\\*.*core'
            line: '*                hard    core            0'
            insertbefore: '^# End of file'

      - name: "AUTOMATED | 1.5.4 | PATCH | Ensure core dumps are restricted"
        sysctl:
            name: fs.suid_dumpable
            value: '0'
            state: present
            reload: yes
            sysctl_set: yes
            ignoreerrors: yes
  when:
      - ubtu18cis_rule_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.4
      - coredump
