---
- name: "AUTOMATED | 4.1.1.1 | PATCH | Ensure auditd is installed"
  apt:
      name: ['auditd', 'audispd-plugins']
      state: present
  when:
      - ubtu18cis_rule_4_1_1_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.1.1
      - auditd

- name: "AUTOMATED | 4.1.1.2 | PATCH | Ensure auditd service is enabled"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
      - ubtu18cis_rule_4_1_1_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.1.2
      - auditd


- name: "AUTOMATED | 4.1.1.4 | PATCH | Ensure audit_backlog_limit is sufficient"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit_backlog_limit={{ ubtu18cis_audit_back_log_limit }})(?:")'
      replace: '\1"\2 audit_backlog_limit={{ ubtu18cis_audit_back_log_limit }}"'
  ignore_errors: yes
  notify: grub update
  when:
      - ubtu18cis_rule_4_1_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.1.4
      - auditd
