---
- name: "AUTOMATED | 4.2.1.1 | PATCH | Ensure rsyslog is installed"
  apt:
      name: rsyslog
      state: present
  when:
      - ubtu18cis_rule_4_2_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.1.1
      - rsyslog
      - apt

- name: "AUTOMATED | 4.2.1.2 | PATCH | Ensure rsyslog Service is enabled"
  service:
      name: rsyslog
      enabled: yes
  when:
      - ubtu18cis_rule_4_2_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.1.2
      - rsyslog

- name: "AUTOMATED | 4.2.1.4 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode|^#\$FileCreateMode'
      line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
      - ubtu18cis_rule_4_2_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.1.4
      - rsyslog

- name: "AUTOMATED | 4.2.1.5 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  blockinfile:
      path: /etc/rsyslog.conf
      block: |
          ##Enable sending of logs over TCP add the following line:
          *.* @@{{ ubtu18cis_remote_log_server }}
      insertafter: EOF
  when:
      - ubtu18cis_rule_4_2_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.1.5
      - rsyslog

- name: "MANUAL | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts"
  block:
      - name: "MANUAL | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts | When not a log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '({{ item }})'
            replace: '#\1'
        with_items:
            - '^(\$ModLoad)'
            - '^(\$InputTCPServerRun)'
        notify: restart rsyslog
        when: not ubtu18cis_system_is_log_server

      - name: "MANUAL | 4.2.1.6 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts | When a log server"
        lineinfile:
            path: /etc/rsyslog.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^\$ModLoad|^#\$ModLoad', line: '$ModLoad imtcp' }
            - { regexp: '^\$InputTCPServerRun|^#\$InputTCPServerRun', line: '$InputTCPServerRun 514' }
        notify: restart rsyslog
        when: ubtu18cis_system_is_log_server
  when:
      - ubtu18cis_rule_4_2_1_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_4.2.1.6
      - rsyslog
